# Generated by Django 4.0.4 on 2022-04-21 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoodMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
