# Generated by Django 4.0.4 on 2022-04-21 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0002_alter_neighborhood_creator_alter_neighborhood_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='member',
        ),
        migrations.AddField(
            model_name='profile',
            name='hood',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hood.neighborhood'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoodCreator', to=settings.AUTH_USER_MODEL),
        ),
    ]
