# Generated by Django 4.0.4 on 2022-04-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_remove_post_postimage_post_hood_post_postedby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='servicesName',
            new_name='serviceName',
        ),
        migrations.AddField(
            model_name='business',
            name='bussinessDescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='serviceDescription',
            field=models.TextField(null=True),
        ),
    ]
