# Generated by Django 4.0.4 on 2022-04-21 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0005_rename_servicesname_services_servicename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='hood.neighborhood'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoodCreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='services',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hood.neighborhood'),
        ),
    ]
