# Generated by Django 4.0.4 on 2022-04-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_alter_business_neighborhood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hood.neighborhood'),
        ),
    ]
